### ISSUE TITLE
System.InvalidCastException: 'Unable to cast an object from DBNull to other types.'

### ISSUE THREAD

**Issue by manixHDPRO** [CirrusRedOrg/EntityFrameworkCore.Jet#212]
Hi, application has worked perfectly well for the past 5 days when I try to connect it shows me this error
![Capture d'écran 2024-01-25 111418](https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/assets/66430995/c9560f4a-fe05-4460-a2c2-ddc231191fdc)

please help me and thank you in advance

**Comment by ChrisJollyAU** [comment]
Can I ask what version of EFCore.Jwt are you on and what version of .Net? 

Also, is that a `MySqlCommand` that I see on the one line? Is that your own class otherwise this could be something with MySql and not Jet/MS Access. Please confirm

**Comment by manixHDPRO** [comment]
the .Net version that I use is 4.6.2 for a desktop application, the connection I use Mysql in an online server before it worked at the cost only like that the error at the connection level

**Comment by ChrisJollyAU** [comment]
This looks to be the wrong place that are you asking in. This repository is for the .Net (Core) Entity Framework provider for Jet/MS Access. As you are using MySql (which is a different provider) this question would be better with the respective provider.

As a general tip, check your data to see if it is correct. Also check if there are any queries/stored procedures etc that execute on connection
