### ISSUE TITLE
If no driver is installed - Exception uncatched

### ISSUE THREAD

**Issue by shwedberlin** [CirrusRedOrg/EntityFrameworkCore.Jet#239]
If no suitable driver is installed on the machine this code throws exception:

https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/blob/4dda3e41d5e2e55beb87b2efb20a576c7dcd7c9a/src/EFCore.Jet.Data/JetConnection.cs#L586

The message in log in this case does not say the problem:
`
An error occurred using the connection to database '""' on server '"File.accdb"'.
`
`
System.InvalidOperationException: Sequence contains no elements
`

**Comment by ChrisJollyAU** [comment]
A better error message is now thrown in beta 1
