### ISSUE TITLE
support for 8.0.6

### ISSUE THREAD

**Issue by mahdiyar021** [CirrusRedOrg/EntityFrameworkCore.Jet#240]
NU1608: Detected package version outside of dependency constraint: EntityFrameworkCore.Jet 7.0.3 requires Microsoft.EntityFrameworkCore (>= 7.0.10 && < 8.0.0) but version Microsoft.EntityFrameworkCore 8.0.6 was resolved.
NuGet\Install-Package : NU1107: Version conflict detected for Microsoft.EntityFrameworkCore.Relational. Install/reference Microsoft.EntityFrameworkCore.Relational 8.0.6 
directly to project Datanex.Backend.Infrastructure to resolve this issue. 
 Datanex.Backend.Infrastructure -> Datanex.Shared.Logic -> Microsoft.EntityFrameworkCore.Relational (>= 8.0.6) 
 Datanex.Backend.Infrastructure -> EntityFrameworkCore.Jet 7.0.3 -> Microsoft.EntityFrameworkCore.Relational (>= 7.0.10 && < 8.0.0).
At line:1 char:1
+ NuGet\Install-Package EntityFrameworkCore.Jet -Version 7.0.3

**Comment by ChrisJollyAU** [comment]
Hi

7.0.3 is part of the series targeting EF Core 7. That error is expected as you can only use it with the specific series.

You are using EF Core 8 so you need the specific series of EFCore.Jet to target that. There is a version for EF Core 8 which is currently in release candidate form. Barring any major critical bug, the RC is almost literally what will become stable.

You need to install the pre-release version of `8.0.0-rc.1`

Below is the package manager command like what you have shown above but with the correct version

`NuGet\Install-Package EntityFrameworkCore.Jet -Version 8.0.0-rc.1`

**Comment by mahdiyar021** [comment]
tnx

**Comment by ChrisJollyAU** [comment]
Just a note that stable 8.0 series is out now
